# Custom Language File for Launcher Customizer

[ejs.app]
title = "Siprev Launcher"

[ejs.landing]
mediaGitHubURL = "http://siprev.byethost22.com"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/BcJaVgstJp"

[ejs.settings]
sourceGithubLink = "http://siprev.byethost22.com"
supportLink = "http://siprev.byethost22.com/issues"

[ejs.welcome]
welcomeHeader = "Hejaaaa"
welcomeDescription = "Mam nadzieję ze spodoba wam się Launcher :>"
welcomeDescCTA = "Pss jebałem się z nim jakoś kilka dni..."
