# Custom Language File for Launcher Customizer

[ejs.app]
title = "Siprev Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/SIPREV/Siprev-Launcher-"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/BcJaVgstJp"

[ejs.settings]
sourceGithubLink = "https://github.com/SIPREV/Siprev-Launcher-"
supportLink = "https://github.com/SIPREV/Siprev-Launcher-/issues"

[ejs.welcome]
welcomeHeader = "Hejaaaa"
welcomeDescription = ""
welcomeDescCTA = ""
